# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718495118868793b27625e251992d823060843163fad98619ca64df46c28725732497ca589464603b02018d86d07953774cfb10db1d56c650dd388a9fd7f4f67

test:
  secret_key_base: 77101c654ca95d27caa9f0a5a7f13fbd2f4b85cc51c0a7b4afef83c70f6eb993154f589d6a9cdcae3cd4204b02bd053c024aca141406ab02eb780403fc0db4e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
